"""Initial migration: create users, clients, vehicles, and work_orders tables

Revision ID: 5e0e375f369c
Revises: 
Create Date: 2025-11-14 00:23:17.689232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0e375f369c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EMPLOYEE', name='user_role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_type', sa.String(length=25), nullable=False),
    sa.Column('brand_model', sa.String(length=50), nullable=False),
    sa.Column('kilometers', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=25), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('egress_date', sa.Date(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('work_status', sa.Enum('PENDING', 'COMPLETED', name='work_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('NOT_PAID', 'PAID', 'BILL_SENT', 'NOT_REQUESTED', name='payment_status'), nullable=False),
    sa.Column('refrigerant_gas_retrieved', sa.Integer(), nullable=True),
    sa.Column('refrigerant_gas_injected', sa.Integer(), nullable=True),
    sa.Column('oil_retrieved', sa.Integer(), nullable=True),
    sa.Column('oil_injected', sa.Integer(), nullable=True),
    sa.Column('detector', sa.Boolean(), nullable=True),
    sa.Column('spare_parts', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('workers', sa.String(length=50), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['Vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_orders')
    op.drop_table('Vehicles')
    op.drop_table('Users')
    op.drop_table('Clients')
    # ### end Alembic commands ###
