"""update schema to match models

Revision ID: b5ad31ff066d
Revises: 5e0e375f369c
Create Date: 2025-11-19 04:16:17.329764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ad31ff066d'
down_revision: Union[str, Sequence[str], None] = '5e0e375f369c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types first
    user_role_enum = sa.Enum('ADMIN', 'EMPLOYEE', name='user_role')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    
    work_status_enum = sa.Enum('PENDING', 'COMPLETED', name='work_status')
    work_status_enum.create(op.get_bind(), checkfirst=True)
    
    payment_status_enum = sa.Enum('NOT_PAID', 'PAID', 'BILL_SENT', 'NOT_REQUESTED', name='payment_status')
    payment_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Add role column as nullable first
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'EMPLOYEE', name='user_role'), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE users SET role = 'EMPLOYEE' WHERE role IS NULL")
    # Make it NOT NULL
    op.alter_column('users', 'role', nullable=False)
    
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_constraint(op.f('vehicles_plate_number_key'), 'vehicles', type_='unique')
    op.drop_constraint(op.f('fk_owner_id'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'clients', ['owner_id'], ['id'], ondelete='CASCADE')
    
    # Add work_status column as nullable first
    op.add_column('work_orders', sa.Column('work_status', sa.Enum('PENDING', 'COMPLETED', name='work_status'), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE work_orders SET work_status = 'PENDING' WHERE work_status IS NULL")
    # Make it NOT NULL
    op.alter_column('work_orders', 'work_status', nullable=False)
    
    # Add payment_status column as nullable first
    op.add_column('work_orders', sa.Column('payment_status', sa.Enum('NOT_PAID', 'PAID', 'BILL_SENT', 'NOT_REQUESTED', name='payment_status'), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE work_orders SET payment_status = 'NOT_PAID' WHERE payment_status IS NULL")
    # Make it NOT NULL
    op.alter_column('work_orders', 'payment_status', nullable=False)
    op.drop_constraint(op.f('fk_workorder_vehicle_id'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_workorder_client_id'), 'work_orders', type_='foreignkey')
    op.create_foreign_key(None, 'work_orders', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'work_orders', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workorder_client_id'), 'work_orders', 'clients', ['client_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_workorder_vehicle_id'), 'work_orders', 'vehicles', ['vehicle_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('work_orders', 'payment_status')
    op.drop_column('work_orders', 'work_status')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_owner_id'), 'vehicles', 'clients', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint(op.f('vehicles_plate_number_key'), 'vehicles', ['plate_number'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
